# This is the thingy for GitHub to make it do some stuff.
# Aka, "build" and Zip up the Firefox & Chrome versions
# of this extension. Basically similar to how OldTwitter
# does it. (Kinda copied some stuff lol)
name: BetterKick build-n-pack

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js environment.
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1

      # Install the NPM modules that are included with this repo.
      - name: Install NPM packages
        run: npm install

      # Get the ability to unzip.
      - name: Install action-zip
        uses: montudor/action-zip@v1.0.0

      # Run the "src/build.js" script through our newly acquired Node.js environment.
      - name: Run the build node script
        run: node src/build

      # Unzip stuffs.
      - name: Unzip extension
        run: unzip -qq ../BetterKick-Chrome -d BetterKick-Chrome; unzip -qq ../BetterKick-Firefox.zip -d BetterKick-Firefox
        working-directory: ${{ github.workspace }}

      # Upload the ZIP files to the "Artifacts" tab on this action's page.
      ## Firefox
      - name: Upload the Firefox build to the "Artifacts" tab
        uses: actions/upload-artifact@v3.1.3
        with:
          name: BetterKick Firefox Build
          path: ${{ github.workspace }}/BetterKick-Firefox
      ## Chrome
      - name: Upload the Chromium build to the "Artifacts" tab
        uses: actions/upload-artifact@v3.1.3
        with:
          name: BetterKick Chromium Build
          path: ${{ github.workspace }}/BetterKick-Chrome